# -*- coding: utf-8 -*-
"""thermal image

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ecg2VuGh6J9OHOOGvQoISWT-XK3ypmL5
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.ndimage import zoom,rotate
from matplotlib.colors import LinearSegmentedColormap

thermal_data = np.array([
[31.50,31.50,31.75,32.25,32.75,33.00,32.75,32.25],
[32.50,31.25,32.75,32.50,32.75,32.25,33.00,32.25],
[32.50,32.50,32.75,33.00,32.25,32.75,32.75,33.25],
[32.50,32.50,32.50,32.75,32.75,32.75,32.50,32.50],
[32.50,32.75,32.50,32.75,32.50,32.75,32.50,32.25],
[33.00,32.75,32.75,32.25,32.75,32.25,32.00,32.00],
[33.25,32.75,32.50,32.75,32.50,32.75,32.25,32.00],
[33.00,32.75,32.75,31.75,32.25,33.00,32.50,33.00],
])

upsampled_data = zoom(thermal_data,8)
min_temp = 28
max_temp = 37

colors = [(0, 'white'),(0.05, 'violet'),(0.08, 'blue'),(0.15, 'cyan'),(0.2, 'yellow'),(0.4, 'orange'),(0.6, 'red'),(0.8, 'maroon'), (1, 'black')]
cmap = LinearSegmentedColormap.from_list('custom', colors)
plt.imshow(upsampled_data,cmap=cmap, vmin=min_temp, vmax=max_temp, interpolation='bicubic')
plt.show()