# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nr_R6-blUipIQqIjK-Gdc3R3_guOcpKW
"""

import tensorflow as tf
import matplotlib.pyplot as plt
from keras.preprocessing import image

# Load the model
model_path = 'path_to_your_model/saved_model'
loaded_model = tf.keras.models.load_model(model_path)

# Function to make prediction
def make_prediction(input_array, model):
    processed_input = preprocess_input_array(input_array)

    # Display the processed input
    plt.imshow(processed_input[0, :, :, 0], cmap='hot')
    plt.axis('off')
    plt.show()

    # Make prediction
    result = model.predict(processed_input)
    if result[0][0] >= 0.5:
        prediction = 'HUMAN'
    else:
        prediction = 'NO'
    print("Prediction:", prediction)

# Example usage with a dummy array from the AMG8833 sensor
dummy_input_array = np.random.randint(0, 255, (8, 8))
make_prediction(dummy_input_array, loaded_model)